### ISSUE TITLE
Cannot Resolve Symbol "LibOpenConnect" And Infradead

### ISSUE THREAD

**Issue by Taimoor-AbdULLAH** [cernekee/ics-openconnect#16]
Code is not Working, Cannot Resolve Symbol "LibOpenConnect" And "Infradead"
Please Any Solution. to this...
![capture](https://cloud.githubusercontent.com/assets/12396371/25042762/e5eaa72c-2133-11e7-937c-1d4e5b6be1bc.PNG)

**Comment by Taimoor-AbdULLAH** [comment]
Can AnyOne Help me out about this issue on My Side.?

**Comment by schemacs** [comment]
@Taimoor-AbdULLAH build the wrapper jar with `make -C external NDK=/opt/android-ndk-r10d`
