### ISSUE TITLE
missing required library

### ISSUE THREAD

**Issue by emanf** [cernekee/ics-openconnect#3]
hi,
after i import ics-openconnect to eclipse i got some error about "missing required library".
<code>
Project 'OpenConnect' is missing required library: 'libs/openconnect-wrapper.jar'	OpenConnect		Build path	Build Path Problem
</code>
<code>
Project 'OpenConnect' is missing required library: 'libs/stoken-wrapper.jar'	OpenConnect		Build path	Build Path Problem
</code>
<code>
The project cannot be built until build path errors are resolved	OpenConnect		Unknown	Java Problem
</code>

where can i download these libraries?
Did I do something wrong? or how can i import it to eclipse or android-studio ?

**Comment by cernekee** [comment]
The .jar and .so files are built by the "Recompiling the external dependencies" step listed in the README.
