### ISSUE TITLE
feature request: Quick Settings Tiles for faster toggling vpn

### ISSUE THREAD

**Issue by aminmazi** [cernekee/ics-openconnect#31]
Hi 
Thanks for such a good project
please add custom quick settings tile for toggling vpn on or off, It is very useful feature that the other vpn clients have.
an example is [here](https://medium.com/google-developers/quick-settings-tiles-e3c22daf93a8).

**Comment by dlenski** [comment]
Already done in dlenski/ics-openconnect#2, dlenski/ics-openconnect#3.
