### ISSUE TITLE
Problem make -C external NDK=/cygdrive/C/android-ndk-r10d

### ISSUE THREAD

**Issue by mahanamiri** [cernekee/ics-openconnect#4]
$ make -C external NDK=/cygdrive/C/android-ndk-r10d
make: Entering directory '/home/Mahan/ics-openconnect/external'
rm -rf arm/openconnect
mkdir -p arm/openconnect
cp -a openconnect arm/
make -C arm/openconnect/android ARCH=arm NDK=/cygdrive/C/android-ndk-r10d
make[1]: Entering directory '/home/Mahan/ics-openconnect/external/arm/openconnect/android'
mkdir -p /home/Mahan/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain
/cygdrive/C/android-ndk-r10d/build/tools/make-standalone-toolchain.sh --platform=android-14 --arch=arm --install-dir=/home/Mahan/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain || \
        /cygdrive/C/android-ndk-r10d/build/tools/make-standalone-toolchain.sh \
                --platform=android-14 --arch=arm --install-dir=/home/Mahan/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain --system=linux-x86_64
Auto-config: --toolchain=arm-linux-androideabi-4.8
Host system 'cygwin-x86' is not supported by the source NDK!
Try --system=<name> with one of:  windows-x86_64
Auto-config: --toolchain=arm-linux-androideabi-4.8
Host system 'linux-x86_64' is not supported by the source NDK!
Try --system=<name> with one of:  windows-x86_64
Makefile:75: recipe for target '/home/Mahan/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain/.built' failed
make[1]: *** [/home/Mahan/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain/.built] Error 1
make[1]: Leaving directory '/home/Mahan/ics-openconnect/external/arm/openconnect/android'
Makefile:103: recipe for target 'arm/libopenconnect.so' failed
make: *** [arm/libopenconnect.so] Error 2
make: Leaving directory '/home/Mahan/ics-openconnect/external'

**Comment by cernekee** [comment]
```
Host system 'cygwin-x86' is not supported by the source NDK!
Try --system= with one of: windows-x86_64
```

You can try tweaking the Makefiles under external/ to see if those components will build under Windows, but it wouldn't be too surprising if other issues popped up.  It's probably easier just to install an Ubuntu Trusty VM and run the build under there.

**Comment by mahanamiri** [comment]
Thanks. I will check it out and tell you the results

**Comment by mahanamiri** [comment]
Hi , New Problem on Ubuntu 15.04 :

cp -a openconnect arm/
make -C arm/openconnect/android ARCH=arm NDK=/Desktop/android-ndk-r10e
make[1]: Entering directory '/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android'
mkdir -p /home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain
/Desktop/android-ndk-r10e/build/tools/make-standalone-toolchain.sh --platform=android-14 --arch=arm --install-dir=/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain || \
	/Desktop/android-ndk-r10e/build/tools/make-standalone-toolchain.sh \
		--platform=android-14 --arch=arm --install-dir=/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain --system=linux-x86_64
/bin/sh: 1: /Desktop/android-ndk-r10e/build/tools/make-standalone-toolchain.sh: not found
/bin/sh: 2: /Desktop/android-ndk-r10e/build/tools/make-standalone-toolchain.sh: not found
Makefile:75: recipe for target '/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain/.built' failed
make[1]: *** [/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain/.built] Error 127
make[1]: Leaving directory '/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android'
Makefile:103: recipe for target 'arm/libopenconnect.so' failed
make: *** [arm/libopenconnect.so] Error 2
make: Leaving directory '/home/mahan/Desktop/ics-openconnect/external'

**Comment by cernekee** [comment]
> make -C arm/openconnect/android ARCH=arm NDK=/Desktop/android-ndk-r10e

Try: `NDK=$HOME/Desktop/android-ndk-r10e`

**Comment by mahanamiri** [comment]
:(( : 

mahan@mahan-VirtualBox:~/Desktop/ics-openconnect/external$ make -C arm/openconnect/android ARCH=arm NDK=/$Home/Desktop/android-ndk-r10e
make: Entering directory '/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android'
mkdir -p /home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain
//Desktop/android-ndk-r10e/build/tools/make-standalone-toolchain.sh --platform=android-14 --arch=arm --install-dir=/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain || \
	//Desktop/android-ndk-r10e/build/tools/make-standalone-toolchain.sh \
		--platform=android-14 --arch=arm --install-dir=/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain --system=linux-x86_64
/bin/sh: 1: //Desktop/android-ndk-r10e/build/tools/make-standalone-toolchain.sh: not found
/bin/sh: 2: //Desktop/android-ndk-r10e/build/tools/make-standalone-toolchain.sh: not found
Makefile:75: recipe for target '/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain/.built' failed
make: *** [/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android/arm-linux-androideabi/toolchain/.built] Error 127
make: Leaving directory '/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android'
mahan@mahan-VirtualBox:~/Desktop/ics-openconnect/external$

**Comment by mahanamiri** [comment]
please help me .

**Comment by mahanamiri** [comment]
checking whether vsnprintf works... probably
configure: WARNING: cannot check for properly working vsnprintf when cross compiling, will assume it's ok
checking whether sscanf needs writable input... no
checking for struct pst_processor.psp_iticksperclktick... no
checking for suitable m4... configure: error: No usable m4 in $PATH or /usr/5bin (see config.log for reasons).
Makefile:185: recipe for target 'arm-linux-androideabi/gmp/Makefile' failed
make[1]: *** [arm-linux-androideabi/gmp/Makefile] Error 1
make[1]: Leaving directory '/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android'
Makefile:103: recipe for target 'arm/libopenconnect.so' failed
make: *** [arm/libopenconnect.so] Error 2
make: Leaving directory '/home/mahan/Desktop/ics-openconnect/external'

**Comment by mahanamiri** [comment]
ohhh : sudo apt-get install m4

**Comment by mahanamiri** [comment]
cd .. && ./autogen.sh
./autogen.sh: 4: ./autogen.sh: libtoolize: not found
Makefile:389: recipe for target '../configure' failed
make[1]: *** [../configure] Error 127
make[1]: Leaving directory '/home/mahan/Desktop/ics-openconnect/external/arm/openconnect/android'
Makefile:103: recipe for target 'arm/libopenconnect.so' failed
make: *** [arm/libopenconnect.so] Error 2
make: Leaving directory '/home/mahan/Desktop/ics-openconnect/external'
mahan@mahan-VirtualBox:~/Desktop/ics-openconnect$

**Comment by cernekee** [comment]
You should have `m4` and `libtoolize` binaries if the autoconf, automake, and libtool packages are installed on your system.

**Comment by mahanamiri** [comment]
Thank you for help
