### ISSUE TITLE
openconnect not working android 10

### ISSUE THREAD

**Issue by naziur604** [cernekee/ics-openconnect#57]
i have a issue its not working on android 10
i dont know whats the prob 
please let me know

**Comment by kmchmk1026** [comment]
Try this.
https://play.google.com/store/apps/details?id=com.github.digitalsoftwaresolutions.openconnect

**Comment by kmchmk** [comment]
> i have a issue its not working on android 10
> i dont know whats the prob
> please let me know

Try this.
https://play.google.com/store/apps/details?id=com.github.digitalsoftwaresolutions.openconnect

**Comment by naziur604** [comment]
> > i have a issue its not working on android 10
> > i dont know whats the prob
> > please let me know
> 
> Try this.
> https://play.google.com/store/apps/details?id=com.github.digitalsoftwaresolutions.openconnect

your app working but i have compiled openconnect its working android 4.x to 9.x all
only not working android 10

**Comment by fariya12** [comment]
@naziur604  have you found an solution to this...??
